### ISSUE TITLE
NoSuchMethodError after upgrading from 11.2 to 12.0

### ISSUE THREAD

**Issue by erkieh** [micronaut-projects/micronaut-data#3369]
### Expected Behavior

After overriding a CrudRepository method in micronaut-data 12.0 we are getting NoSuchmethod errors in Runtime

### Actual Behaviour

Below is the difference between kapt generated repository intercepted classes
<img width="2049" alt="Image" src="https://github.com/user-attachments/assets/ccde0151-a776-4c18-aeee-5ecab1216c22" />
notice **this.** vs **super.** usage

### Steps To Reproduce

Override method in repository

```
@JdbcRepository(dialect = Dialect.POSTGRES)
interface DocumentRepository : CrudRepository<Document, UUID> {

    @JoinSpecifications(
        Join(value = "folder", type = Join.Type.LEFT_FETCH)
    )
    override fun findById(id: UUID): Optional<Document>
}
```

### Environment Information

jdk 21

### Example Application

https://github.com/erkieh/micronaut-data-repoid

### Version

4.12
