### ISSUE TITLE
Entity with public fields not supported

### ISSUE THREAD

**Issue by radovanradic** [micronaut-projects/micronaut-data#2615]
### Expected Behavior

Having an entity
```
@MappedEntity
public class ExampleDomain {

    @Id
    public Long id;

    public String name;
}
```
and repository 
```
@JdbcRepository(dialect = Dialect.H2)
public interface ExampleDomainRepository extends CrudRepository<ExampleDomain, Long> {

    ExampleDomain findByName(String name);
}
```
Repository should support `findById` and custom `findByName` method.

### Actual Behaviour

The compiler error is thrown:

```Unable to implement Repository method: ExampleDomainRepository.update(Object entity). No identity is present```

Also won't be able to implement findByName complaining

```Unable to implement Repository method: ExampleDomainRepository.findByName(String name). Cannot query entity [ExampleDomain] on non-existent property: Name```

### Steps To Reproduce

Just try to create repository for the entity above.

### Environment Information

Any

### Version

3.x, 4.x

**Comment by graemerocher** [comment]
not sure if this is a bug, the user would need to specify the access kind. See https://docs.micronaut.io/latest/api/io/micronaut/core/annotation/Introspected.html#accessKind()

**Comment by radovanradic** [comment]
I tried this 
```
@MappedEntity
@Introspected(accessKind = Introspected.AccessKind.FIELD)
public class ExampleDomain {

    @Id
    public Long id;

    public String name;
}
```
and getting the same compilation errors.

**Comment by radovanradic** [comment]
Tried again `@Introspected(accessKind = Introspected.AccessKind.FIELD)` and it seems it works in 4.10.0
Closing issue.
